- name: Install CRI-O container runtime
  hosts: kubernetes
  become: yes
  become_method: sudo
  vars:
  - VERSION: v1.27
  tasks: 
  - ansible.builtin.apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gpg
      state: present
      update_cache: yes
#  - ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ VERSION }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - ansible.builtin.apt_key:
      url: https://pkgs.k8s.io/core:/stable:/{{ VERSION }}/deb/Release.key
      state: present
  - ansible.builtin.apt_repository:
      repo: deb https://pkgs.k8s.io/core:/stable:/{{ VERSION }}/deb/ /
      state: present
  - ansible.builtin.apt:
      pkg:
        - kubelet
        - kubeadm
        - kubectl
      state: present
      update_cache: yes
  - ansible.builtin.dpkg_selections:
      name: kubelet
      selection: hold
  - ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: hold
  - ansible.builtin.dpkg_selections:
      name: kubectl
      selection: hold
  - blockinfile:
      path: /etc/sysctl.d/99-kubernetes-cri.conf
      create: yes
      block: |
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
  - blockinfile:
      path: /etc/modules
      create: yes
      block: |
        overlay
        br_netfilter
