- name: Install Docker container runtime
  hosts: docker-worker
  become: yes
  become_method: sudo
  tasks: 
  - apt:
      pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
      update_cache: yes
  - apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present
      update_cache: yes
  - apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
  - apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes
  - user:
      name: ubuntu
      groups: docker
      append: yes
  - get_url:
      url: https://github.com/docker/compose/releases/download/1.28.4/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755
