- name: Install Docker container runtime
  hosts: crio-worker
  become: yes
  become_method: sudo
  tasks: 
  - apt:
      pkg:
        - docker
        - docker-engine
        - docker.io
        - containerd
        - runc
      state: absent
      update_cache: yes
  - apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present
      update_cache: yes
  - apt_repository:
      repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /
      state: present
  - apt_repository:
      repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.17/xUbuntu_18.04/ /
      state: present
  - apt_key:
      url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.17/xUbuntu_18.04/Release.key"
      state: present
  - apt_key:
      url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key"
      state: present
  - apt:
      pkg:
        - cri-o 
        - cri-o-runc
        - runc
      state: present
      update_cache: yes
  - systemd:
      name: crio
      state: started
      enabled: True
